import Navbar from "./components/Navbar"
import { Poppins } from "next/font/google"

const poppins = Poppins({
  weight: ["100", "400", "700", "900"],
  subsets: ["latin"],
  variable: "--font-primary",
})

import "./globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.variable}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
